### ISSUE TITLE
jsane doesnt support keys with spaces

### ISSUE THREAD

**Issue by infinite-Joy** [skorokithakis/jsane#4]
the value below gives syntax error

```
>>> j = jsane.from_dict({"hi x": "there"})
>>> j."hi x"
  File "<stdin>", line 1
    j."hi x"
           ^
SyntaxError: invalid syntax
```

**Comment by skorokithakis** [comment]
Yes, this is because Python doesn't allow spaces in property names. You can work around this by using attribute notation (`j["hi x"].r()`).
